### ISSUE TITLE
BridgeContainer generates IDs outside of specification

### ISSUE THREAD

**Issue by ddelbondio** [SURFnet/Stepup-saml-bundle#48]
The ID generation of the BridgeContainer does not conform to the SAML specification. The IDs are specified as https://www.w3.org/TR/xmlschema-2/#ID in the schema, but using base64_encode can cause IDs with invalid characters (like + and /) to be generated. A better solution here would probably be bin2hex (although this increases the ID size)

**Comment by DRvanR** [comment]
Hello,

thanks for the report, this is indeed not correct. The alternative sounds like a good solution! Will try to get round to fixing it this week, but can't promise anything. If possible, could you also make an accompanying PR?

Thanks again!

**Comment by DRvanR** [comment]
The fix for this issue ( #49 ) is release as part of release 2.5.0

**Comment by ddelbondio** [comment]
Thanks for the quick fix!
